public enum AbilityType{NONE,STR,DEX,CON,INT,WIS,CHA}
public enum CharacterSize{TINY,SMALL,MEDIUM,LARGE,HUGE,GARGANTUAN}
public enum DiceType{D2,D3,D4,D6,D8,D10,D12,D20,D100 }
public enum SkillType{ACROBATICS,ANIMAL_HANDLING,ARCANA,ATHLETICS,DECEPTION,HISTORY,INSIGHT,INTIMIDATION,INVESTIGATION,
    MEDICINE,NATURE,PERCEPTION,PERFORMANCE,PERSUASION,RELIGION,SLEIGHT_OF_HAND,STEALTH,SURVIVAL}
#region wepaonEnums
public enum WeaponGroup{NO_WEAPON,SIMPLE_MELEE,SIMPLE_RANGED,MARTIAL_MELEE,MARTIAL_RANGE} 

public enum WeaponType{
//simple melee
NO_WEAPON,CLUB,DAGGER,GREATCLUB,HANDAXE,JAVELIN,LIGHT_HAMMER,MACE,QUATERSTAFF,SICKLE,SPEAR,
//simple ranged
CROSSBOW_LIGHT,DART,SHORTBOW,SLING,
//martial melee
BATTLEAXE,FLAIL,GLAIVE,GREATAXE,GREATSWORD,HALBERD,LANCE,LONGSWORD,MAUL,MORNINGSTAR,PIKE,RAPIER,SCIMITHAR,SHORTSWORD,TRIDENT,WAR_PICK,WARHAMMER,WHIP,
//martial ranged
BLOWGUN,CROSSBOW_HAND,CROSSBOW_HEAVY,LONGBOW,NET} 
public enum DamageType{BLUDGEONING,PIERCING,SLASHING,NONE}
public enum WeaponProperty{AMMUNITION,FINESE,HEAVY,LIGHT,LOADING,REACH,SPECIAL,THROWN,TWO_HANDED,VERSATILE,NONE}
#endregion
public enum ArmorGroup{LIGHT,MEDIUM,HEAVY,SHIELD}
public enum ArmorType{NO_ARMOR,PADDED,LEATHER,STUDDED_LEATHER,HIDE,CHAIN_SHIRT,SCALE_MAIL,BREASTPLATE,HALFPLATE,
RING_MAIL,CHAIN_MAIL,SPLINT,PLATE,SHIELD}